language: python
python: 3.5
env:
  matrix:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=py27
  - TOXENV=py26
  - TOXENV=pypy
install: pip install -U tox
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: timmartin19
  password:
    secure: A4KghZC6jFA4s5gF7gROXnwaoRFZZw3FhePZ/9HaUjaHBVJbjvrYHUI/Pn2EBReu39/bqyBRVqo3g1NBNqqWZ0LndDDTmj3W1hE2UMU1Ql9RBSyr092ibnlq5A6yP0045ma4jCEWw55QLvojknt0wtwyoTJtKadke0xERqobD4rOWVANrfhk5c0ONB5y1lh467OR+Eu/CK4kQzbnoKNe224vfDzjYH4/LSJ/nxciu5j6ZuQ5Qqno+ZS2SYd+cUcYk0UOOo0bOGCh1Jbgui7AVuG/ktJENSIISnLnlIwZ0RKXDVGdI4+7esr56lleVVdzWB+y0JqXrN8CB+tqtUqFbc2NXm5cVYDwblbPXNtB3lD1f/Xp8PuulvvzHOfosTi3zTRm4p2XrkL2Op14/iFZo+/+QxloWG0mBsqXvvmvUA3Y58OGyKj65v4i78tUClqJivZMylfU/mdtO6RaEQc9e9/truMBzaguAvAUg1fWXli81ZM8xzbA5Rn5Ke7zCs/GSi85T1LTEbLI3GpkjPxwId7Il7icKiDIkv8RBCF+lY2fNqkpDVzPxYyJnTKMhjbYXrbZRjispAArWtiLQh/QYlSYWh1jvWbfLvgA/6UN1U43N4WArSQdPRHa9bAjArChNOjALSENyINRlhD9hj413XlTK0AAWoa9Hzo5P/FnRyg=
  on:
    branch: master
    repo: timmartin19/pystatuschecker
    condition: $TOXENV == py27
